import type { Metadata } from 'next';
import Link from 'next/link';
import { builtInWorkflows } from '@/lib/workflow-library';
import { providerPresets } from '@/lib/providers';

export const metadata: Metadata = { title: '使用教程 · 智能搭子导演工作台', description: '本地系统条件、安装准备、模型与工作流清单、剧本到视频测试的完整操作指南' };
const chapters = [['requirements','本地系统条件'],['install','安装与启动'],['models','模型与工作流'],['api','配置大模型'],['script','第一步：剧本'],['images','第二步：参考图'],['video','第三步：视频测试'],['logs','系统日志'],['backup','保存与安全'],['faq','常见问题']] as const;
const modelFolder = (type: string) => ['UNETLoader', 'UnetLoaderGGUF'].includes(type) ? 'diffusion_models' : type === 'CLIPLoader' ? 'text_encoders' : type === 'VAELoader' ? 'vae' : 'loras';

export default function Tutorial() {
  return <main className="tutorial-page">
    <aside className="tutorial-note mx-4">参考图支持本地与线上多种方式：进入“02 参考图”，在顶部选择项目默认方式；需要时可在单张素材右侧临时改为“仅本地”“仅阿里云”或“仅 Seedream”。切换不会删除已有图片。</aside>
    <header className="tutorial-header"><strong>智能搭子导演工作台 / 使用教程</strong><Link href="/">打开导演台 →</Link></header>
    <div className="tutorial-layout"><nav aria-label="教程目录"><p className="font-semibold">从安装到第一次出图</p>{chapters.map(([id,title],i) => <a key={id} href={`#${id}`}>{String(i+1).padStart(2,'0')} · {title}</a>)}<p className="mt-5 text-sm text-muted-foreground">教程独立打开。切回原来的导演台标签页，即可继续当前操作。</p></nav>
    <article className="tutorial-content"><h1>本地制作，一步一步来</h1><p>无需安装 Codex。你需要分别准备导演台、ComfyUI 和模型文件；导演台不会自动下载模型。先完成一个剧情段落的测试，再推进整部短剧。</p><aside className="tutorial-note">第一次使用顺序：检查电脑 → 启动两个服务 → 配置分析 API → 导入剧本 → 生成并采用参考图 → 测试视频。下面的文件名对应当前内置模板，不代表模型官方最低配置。</aside>
    <section id="requirements"><h2>01 / 本地需要满足哪些条件？</h2><div className="tutorial-table"><table><thead><tr><th>项目</th><th>条件与说明</th></tr></thead><tbody>
      <tr><td>操作系统</td><td>当前本地启动脚本面向 Windows。其他系统尚未完成本项目验证，不能直接使用 .cmd / .ps1 启动方式。</td></tr>
      <tr><td>导演台运行环境</td><td>Node.js 22.13 或更高版本，附带 npm；以 package.json 的 engines 要求为准。仅编辑剧本、配置 API 不需要本地 GPU。</td></tr>
      <tr><td>浏览器</td><td>需支持 JavaScript、本地存储、文件上传与视频播放。请固定使用同一个浏览器和地址；小窗口内部分内容会在面板中滚动。</td></tr>
      <tr><td>本地生图与视频</td><td>ComfyUI 必须独立安装并能运行选定模型。显卡、驱动、PyTorch 与量化格式必须相互兼容；NVFP4 不能仅凭显存容量判断可用。</td></tr>
      <tr><td>本地生图配置</td><td>统一使用 Qwen Image 2.1 INT8 主模型与编码器。RTX 5070 12GB 的速度与显存峰值需实机验收；建议从单张母版开始，再增加参考图数量。</td></tr>
      <tr><td>H3 视频资源</td><td>不同模型、时长、分辨率和卸载策略的资源需求不同。本教程不承诺统一最低显存；请先在 ComfyUI 中单独跑通对应视频工作流。</td></tr>
      <tr><td>磁盘空间</td><td>需准备 Qwen Image 2.1 主模型、文本编码器与专用 VAE；H3 视频模型、缓存与输出另计。</td></tr>
      <tr><td>网络与端口</td><td>安装依赖、下载模型和调用云端分析 API 需要联网。默认导演台 3000、ComfyUI 8188，端口不能被其他程序占用。本地代理只接受本机地址，不支持任意远程服务器。</td></tr>
    </tbody></table></div><p>已下载的模型由本机 ComfyUI 执行；大模型 API 是另一项服务，分析剧本会产生供应商用量。不要将“本地导演台”理解为“全部流程无需联网或 API”。</p></section>
    <section id="install"><h2>02 / 安装与启动</h2><h3>A. 先启动 ComfyUI</h3><ol><li>将 ComfyUI 安装到独立目录，不要把模型放进导演台的 public 或 node_modules。</li><li>按下一章准备模型和自定义节点，然后使用 ComfyUI 自身的启动方式启动。</li><li>打开 <a href="http://127.0.0.1:8188/" target="_blank" rel="noreferrer">本机 ComfyUI</a>。页面能打开仅表示服务在线，还需要跑通工作流。</li></ol><h3>B. 再启动导演台</h3><p>在本项目目录打开 PowerShell。先运行下面两条命令检查版本：</p><pre>node --version{'\n'}npm --version</pre><p>首次安装与启动：</p><pre>npm install{'\n'}npm run build{'\n'}npm run start</pre><p>保持启动终端运行，打开 <a href="http://127.0.0.1:3000/">http://127.0.0.1:3000/</a>。Windows 也可双击项目中的 start-local.cmd；首次构建可能需要等待。修改源码后重新构建并重启，刷新页面才能看到新版本。</p><p>开发时可用 npm run dev，并以终端实际显示的地址为准。同一端口不要同时启动开发版和本地构建版。</p><h3>C. 检查连接</h3><p>首页右上角 → 连接与设置 → 填写 http://127.0.0.1:8188 → 检测连接、节点与模型。生图环境和当前视频模板是分别检查的；换视频模式后请重新检测。</p></section>
    <section id="models"><h2>03 / 准备哪些模型和工作流？</h2><p>系统内置视频、基础生图、动作构图和一致性精修 API 模板，通常不需要手动导入。以下清单直接读取应用配置；文件名必须与加载节点中的选择一致。请从模型作者或节点维护者提供的来源获取，核对说明与校验值，不要只重命名其他权重来消除“缺失”提示。</p>
      {builtInWorkflows.map(w => <details key={w.id} open><summary>{w.name} · {w.requiredImages ? `${w.requiredImages} 张输入图片` : '无需输入图片'}</summary><p>{w.description}</p><p><a href={w.file} download>下载当前 API 工作流 JSON</a>（{w.mode}）</p><ul>{w.requiredModels.map((m,i) => <li key={i}><code>ComfyUI/models/{modelFolder(m.classType)}/{m.filename}</code></li>)}</ul><p>环境预检关注的节点：{w.requiredNodes.join('、')}。这不是完整依赖列表；实际模板中的其他节点也必须存在，最终以 ComfyUI 提交校验为准。</p></details>)}
      <h3>模型准备后的验收</h3><ol><li>把文件放到上述类别目录；重启或刷新 ComfyUI 的模型列表。</li><li>若节点缺失，根据节点类名找到对应维护者的扩展及安装说明。不要随意安装同名陌生扩展。</li><li>先单独运行 Qwen Image 2.1 文生图和参考图编辑，再测试所需 H3 视频模式；模型可选中不等于能成功推理。</li><li>回到导演台重新检测，确认所选模式环境正常。</li></ol><p>手动覆盖入口在“03 视频测试 → 高级”。需要 API Format JSON（节点具有 class_type），不是仅包含 nodes/links 的画布布局 JSON。当前参数注入只适配应用识别的节点类型，并非任意 ComfyUI 图都可直接运行。</p></section>
    <section id="api"><h2>04 / 配置国内大模型 API</h2><h3>剧本分析 API</h3><ol><li>点击“连接与设置 → 剧本分析 API”。</li><li>选择供应商，填写你自己账户的 API Key、已开通的模型名称与兼容接口地址。</li><li>点击“测试连接”；会发送一条短请求，可能产生少量用量。</li><li>成功后“保存并使用”，回到剧本步骤。</li></ol><div className="tutorial-table"><table><thead><tr><th>供应商</th><th>本版本接口预设</th><th>账户入口</th></tr></thead><tbody>{Object.values(providerPresets).map(p => <tr key={p.provider}><td>{p.name}</td><td><code>{p.baseUrl}</code></td><td><a href={p.helpUrl} target="_blank" rel="noreferrer">供应商控制台</a></td></tr>)}</tbody></table></div><h3>线上参考图 API</h3><p>这是独立设置，不会跟随剧本分析供应商自动切换。打开“连接与设置 → 参考图生成方式”，可选择阿里云百炼或火山方舟 Seedream。</p><ul><li>百炼默认 <code>qwen-image-3.0-pro</code>，支持文生图及 1–3 张参考图图生图；工作空间域名和 Key 必须同一区域。</li><li>方舟默认 <code>doubao-seedream-5-0-260128</code>，也可改为 5.0 Lite、4.5 或 4.0 的官方模型 ID；接口为 <code>https://ark.cn-beijing.volces.com/api/v3/images/generations</code>。</li></ul><p>这些服务需要各自独立的 API Key，系统会分别保存在当前标签页。普通聊天产品会员不等于 API 额度；接口域名受白名单限制，不支持第三方中转地址。出现“未配置 API Key，已生成本地规则草稿”只表示没有调用剧本分析模型，与参考图模型无关。</p></section>
    <section id="script"><h2>05 / 第一步：导入并分析剧本</h2><ol><li>选择顶部“01 剧本”，粘贴内容或导入 .md / .txt；长剧本在输入框里滚动。</li><li>剧本尽量明确人物姓名、场景、动作、对白及说话对象。系统不会替你确认原文是否有歧义。</li><li>点击底部“分析剧本”。完成后，右侧“分析结果”可切换剧情概览、分镜 Beat、人物场景和生图计划；展开条目可查看 H3 导演描述或完整生图提示词。</li><li>逐项确认时长、模式、人物状态、连续空间、素材继承与冲突后，点击“下一步：参考图”。</li></ol><h3>什么是 Beat 和冲突？</h3><p>Beat 是一个剧情推进单元，例如“醒来”“发现伤势”“听见脚步”，不等于固定 10 秒。待检查事项是人物、道具、服装、身体状态或空间的潜在矛盾，不表示程序报错。</p><p>重新分析会替换现有段落及素材计划，已采用图片需要重新整理绑定；先导出项目再操作。</p></section>
    <section id="images"><h2>06 / 第二步：制作并验收参考图</h2><ol><li>进入“02 参考图”，先在顶部选择项目默认方式：本地 ComfyUI、阿里云百炼或火山方舟 Seedream。单张素材的下拉框可以覆盖项目默认值。</li><li>使用本地方式时点击“检测本地环境”，系统会检查 Qwen Image 2.1；线上方式不检查本地模型，但仍需要 ComfyUI 在线保存结果并供后续视频使用。</li><li>先生成并采用人物身份母版和连续空间母版。身份母版必须是单人单画面定妆照；禁止使用四宫格、设定板或多视角拼贴。</li><li>本地母版和派生图统一使用 Qwen Image 2.1，派生图最多输入 10 张参考图，输出跟随第一张编辑画布的比例；百炼与 Seedream 都会接收最多 3 张已采用的人物、场景或首帧母版，并明确每张图的继承职责。</li><li>也可在对应素材卡片点击“上传本地图片”，上传后点击缩略图查看原图，逐项确认同一张脸、服装、场景地标、道具状态、手部接触和人物数量；合格点“采用”，不合格修改描述后重做。</li></ol><aside className="tutorial-note">模型和图生图都只能降低漂移，不能代替人工验收。首尾帧仍要核对镜头轴线与构图兼容；包括背景人物在内，所有需要运动的人物都应有合理动作差异。</aside><p>切换生成方式不会重写素材提示词，也不会删除已有结果。线上调用会产生供应商费用。参考图中的声音和对白不属于图片目标，应放在视频描述中。</p></section>
    <section id="video"><h2>07 / 第三步：分镜与整片生成</h2><aside className="tutorial-note">新版可使用右侧“新 Director · 多段与整片”。先检查原文、起止状态、模式理由，再按槽位选图；确认后选择整片或当前分镜。人物身份母版与字面首帧承担不同职责。</aside><ol><li>生图素材服务地址默认8188，新 Director 地址默认8189，分别填写。目标环境需 Thefrizzy1 Director；多图参考还需仓库附带的 MiniMaxH3DirectorWeb 独立适配节点，安装后重启。</li><li>在“描述”选择 T2V、I2V、FL2VA 或 Ref2VA。只有同空间、同机位、可延续动作才勾选上一段末帧接续；转场或换装应关闭。接续段只能随前段生成，不能独立启动。</li><li>在“选图”绑定采用素材。I2V一张完整首帧，FL2VA依次首帧与尾帧，Director多图参考支持1–9张并核对职责。</li><li>选择生成范围、画幅、种子；MP与步数取下方测试参数。逐段计划显示实际帧数与总时长。</li><li>先点“检查 Director 与素材”，只读检查不会运行模型。通过后点生成：图片自动转存到8189 input，一次提交多段接续与合片。</li><li>任务完成后在 Director 面板播放下载。完整观看视频并听声音，检查人物、动作、对白及接缝；静态验证不能证明生成质量。</li></ol><h3>原有单段测试</h3><ol><li>进入“03 视频测试”，在左侧选择当前剧情段落。</li><li>上传自己的图片请在“02 参考图”对应素材卡片完成，并打开原图验收、点击“采用”。然后在本页“选图”中按槽位选择已采用素材，图片 1、图片 2 的顺序会写入最终提示词。FL2VA 的图片 1 是首帧，图片 2 是尾帧。</li><li>在“描述”中检查时长和生成描述，核对对白原文、说话顺序及对象。</li><li>先选择“快速预览 · 0.4 MP”。连接、模板或图片数量不符合要求时，按钮旁会提示原因。</li><li>点击“生成这个段落的测试视频”。不要同时批量堆积视频任务。</li><li>完成后打开“结果”，播放、下载，抽取首中尾帧；听对白并检查人物、空间、道具、表演和连续性。</li><li>点击质检通过或需要重做。通过后可用 0.7 MP 重做，或手动选择下一段继续。</li></ol><div className="tutorial-table"><table><thead><tr><th>模式</th><th>图片与用途</th></tr></thead><tbody><tr><td>T2V</td><td>0 张图片，纯文字生成。</td></tr><tr><td>I2V</td><td>1张完整首帧，或在Director中沿用上一段实际末帧。</td></tr><tr><td>Ref2VA</td><td>旧单段模板2张，新Director可1–9张参考图，用于人物、场景或道具参考；不是字面首尾帧。</td></tr><tr><td>FL2VA</td><td>2 张图片，第一张是开场，第二张是结尾。仅在确实需要同时约束起点与终点时使用，普通动作不必强行首尾帧。</td></tr></tbody></table></div><p>MP 表示总像素量，不是“720P / 1080P”。最终宽高还取决于画幅比例和对齐取整，请以生成文件尺寸为准。抽取三帧只是辅助，不能代替完整视频和音频检查。</p><p>新版Director可自动多段生成与合片；字幕和剪辑工程导出尚未实现。</p></section>
    <section id="logs"><h2>08 / 查看系统日志</h2><p>顶部“04 系统日志”会实时记录剧本分析、ComfyUI 连接、参考图状态、视频任务及质检结果。可以按级别和分类筛选、搜索错误摘要、关闭自动滚动，或导出当前筛选结果。</p><ul><li>日志只记录任务名称、状态、模型方式和错误摘要，不记录 API Key、完整剧本或完整提示词。</li><li>最近 500 条保存在当前浏览器；点击“清空”只删除日志，不会删除图片、视频或项目。</li><li>排查失败时先筛选“错误”，再按时间找到相邻的提交与连接记录；需要更底层的信息时仍应查看 ComfyUI 终端。</li></ul></section>
    <section id="backup"><h2>09 / 保存、迁移与隐私</h2><ul><li>项目草稿在当前浏览器 localStorage 中。localhost 与 127.0.0.1 属于不同站点存储，换地址可能看不到原项目。</li><li>右上角“导出项目”下载 JSON，不包含图片、视频和 API Key。当前没有完整项目包导入恢复入口，不要把导出 JSON 当作一键还原包。</li><li>本地参考图一般在 ComfyUI/output/h3-director-web/assets；线上结果会立即保存到 ComfyUI/input/h3-director-web/cloud，避免供应商临时链接过期。视频在 output/h3-director-web 下。</li><li>剧本分析与线上生图 API Key 都使用会话存储，不写入项目导出。共享电脑请清除密钥；浏览器会话恢复机制可能影响关闭标签页后的保留行为。</li><li>使用云端分析时剧本会发送给分析供应商；使用线上生图时提示词与最多 3 张参考图会发送给生图供应商。不要公开 .env.local、API Key、私人剧本和 ComfyUI 服务端口。</li></ul></section>
    <section id="faq"><h2>10 / 常见问题与排查顺序</h2>{[
      ['网页打不开','先看导演台启动终端是否退出或报错，再确认 3000 端口。ComfyUI 的 8188 是另一个服务，启动其中一个不会自动启动另一个。'],
      ['还是旧版，按钮没反应','确认终端正在运行新构建，按 Ctrl+F5 刷新。不要首先清空浏览器数据，否则可能丢失草稿。'],
      ['无法连接 ComfyUI','先直接打开 127.0.0.1:8188；打不开则检查 ComfyUI 日志与启动状态。能打开再检查导演台填写的地址。远程 IP 暂不支持。'],
      ['缺少节点或模型','按检测结果定位对应模板，核对文件目录、完整文件名与自定义节点依赖，重启后重新检测。仅把其他模型重命名为预期文件名不能解决兼容问题。'],
      ['显存不足或量化加载报错','查看 ComfyUI 原始报错，先停止无关 GPU 任务，再缩小画面或缩短视频。NVFP4/FP4 兼容问题与单纯显存不足不同，需要核对硬件和运行环境。'],
      ['API 测试返回 401 / 403 / 429','依次检查密钥、账户权限和模型是否已开通，以及余额或限流。不要连续重复提交；查看供应商返回的说明。'],
      ['有图片但视频按钮仍不可用','图片必须先采用，再绑定到当前段落。检查数量：T2V 0张、独立I2V 1张、FL2VA 2张，Director多图参考按设置1–9张；检查是否已在“02 参考图”上传并采用。'],
      ['任务长时间排队或提示丢失','去 ComfyUI 查看真实队列与历史。重启或清空历史会导致任务找不到；确认没有同一任务仍在运行后再重试。'],
      ['图片生成成功但人物对不上','确认人物与场景母版已采用，并确认参考图职责与顺序正确。旧版单阶段图片会被标记要求重做；最终仍需打开原图人工验收。'],
    ].map(([q,a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}<p className="mt-6"><a href="#requirements">返回教程顶部 ↑</a></p></section>
    </article></div>
  </main>;
}
